export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const USER_IS_VERIFIED = 'USER_IS_VERIFIED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ALL_PERSONS = 'GET_ALL_PERSONS';
export const GET_ALL_CHIPS = 'GET_ALL_CHIPS';
